'use client'

import React from 'react'
import { useField, useFormFields } from '@payloadcms/ui'
import type {
  TextFieldClientProps,
  TextareaFieldClientProps,
} from 'payload'

import {
  generateInternalTitle,
  generateSlug,
  generateHeroName,
  generateHeroDescription,
} from '@/lib/routeFieldGenerators'

const BRAND = {
  primary: '#1d22d2',
  primaryDark: '#1519a8',
  dark: '#17191f',
  grey: '#68707c',
  border: '#dfe2e8',
  blueLight: '#eef0ff',
  white: '#ffffff',
  font: "'Outfit', Helvetica, sans-serif",
}

const GENERATORS = {
  internalTitle: generateInternalTitle,
  slug: generateSlug,
  heroName: generateHeroName,
  heroDescription: generateHeroDescription,
} as const

type GeneratorKey = keyof typeof GENERATORS

type Props = (
  | TextFieldClientProps
  | TextareaFieldClientProps
) & {
  generatorKey: GeneratorKey
  autoFieldPath: string
  multiline?: boolean
}

export function AutoGeneratedField({
  field,
  path,
  generatorKey,
  autoFieldPath,
  multiline,
}: Props) {
  const { value, setValue } = useField<string>({ path })

  const originCity = useFormFields(
    ([fields]) => fields.originCity?.value as string | undefined,
  )

  const destinationCity = useFormFields(
    ([fields]) => fields.destinationCity?.value as string | undefined,
  )

  const { value: isAuto, setValue: setIsAuto } = useField<boolean>({
    path: autoFieldPath,
  })

  const generator = GENERATORS[generatorKey]

  const preview =
    originCity && destinationCity
      ? generator(originCity, destinationCity)
      : '(fill in Origin City and Destination City first)'

  const locked = isAuto !== false

  const InputTag = multiline ? 'textarea' : 'input'

  return (
    <div
      style={{
        marginBottom: 24,
        fontFamily: BRAND.font,
      }}
    >
      <label
        style={{
          display: 'block',
          marginBottom: 8,
          color: BRAND.dark,
          fontSize: 14,
          fontWeight: 700,
          letterSpacing: '-0.01em',
        }}
      >
        {field.label as string}

        {field.required ? (
          <span style={{ color: '#e04444', marginLeft: 3 }}>
            *
          </span>
        ) : null}
      </label>

      <div
        style={{
          display: 'flex',
          alignItems: multiline ? 'flex-start' : 'center',
          gap: 10,
        }}
      >
        <InputTag
          value={locked ? preview : value ?? ''}
          onChange={(e) => setValue(e.target.value)}
          readOnly={locked}
          rows={multiline ? 4 : undefined}
          style={{
            flex: 1,
            width: '100%',
            minHeight: multiline ? 100 : 44,
            padding: '11px 13px',
            borderRadius: 10,
            border: `1px solid ${
              locked ? '#e5e7eb' : BRAND.border
            }`,
            background: locked ? '#f7f8fa' : BRAND.white,
            color: locked ? '#69707c' : BRAND.dark,
            fontFamily: BRAND.font,
            fontSize: 14,
            lineHeight: 1.55,
            outline: 'none',
            resize: multiline ? 'vertical' : undefined,
            boxSizing: 'border-box',
          }}
        />

        <button
          type="button"
          onClick={() => {
            const nextAuto = !locked

            setIsAuto(nextAuto)

            if (
              nextAuto &&
              originCity &&
              destinationCity
            ) {
              setValue(
                generator(
                  originCity,
                  destinationCity,
                ),
              )
            }
          }}
          style={{
            flexShrink: 0,
            minWidth: 86,
            padding: '10px 14px',
            borderRadius: 9,
            border: `1px solid ${
              locked ? BRAND.border : BRAND.primary
            }`,
            background: locked
              ? BRAND.white
              : BRAND.primary,
            color: locked
              ? BRAND.primary
              : BRAND.white,
            fontFamily: BRAND.font,
            fontSize: 12,
            fontWeight: 700,
            cursor: 'pointer',
            transition: 'all 0.18s ease',
          }}
        >
          {locked ? 'Unlock' : 'Lock'}
        </button>
      </div>

      <div
        style={{
          marginTop: 8,
          color: BRAND.grey,
          fontSize: 12,
          lineHeight: 1.5,
        }}
      >
        {locked
          ? 'Automatically generated from the selected cities.'
          : 'Unlocked — you can manually edit this value.'}
      </div>
    </div>
  )
}

export default AutoGeneratedField