import type { CollectionConfig } from 'payload'
import {
  generateInternalTitle,
  generateSlug,
  generateHeroName,
  generateHeroDescription,
} from '../lib/routeFieldGenerators'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'

export const ShippingRoutePages: CollectionConfig = {
  slug: 'shipping-route-pages',

  admin: {
    useAsTitle: 'internalTitle',
    defaultColumns: ['internalTitle', 'slug', 'rate', 'routeActions', 'updatedAt'],
    group: 'Landing Pages',
    preview: (doc) => `${SITE_URL}/${doc.slug}`,
  },

  access: {
    read: () => true,
  },

  hooks: {
    beforeChange: [
      ({ data }) => {
        const origin = data.originCity?.trim()
        const destination = data.destinationCity?.trim()
        if (!origin || !destination) return data

        if (data.autoInternalTitle !== false) {
          data.internalTitle = generateInternalTitle(origin, destination)
        }
        if (data.autoSlug !== false) {
          data.slug = generateSlug(origin, destination)
        }
        if (data.autoHeroName !== false) {
          data.heroName = generateHeroName(origin, destination)
        }
        if (data.autoHeroDescription !== false) {
          data.heroDescription = generateHeroDescription(origin, destination)
        }
        return data
      },
    ],
  },

  fields: [
    {
      type: 'row',
      fields: [
        {
          name: 'originCity',
          type: 'text',
          required: true,
          defaultValue: 'Delhi',
          label: 'Origin City',
          admin: {
            width: '50%',
            description: 'Used in H1 and subhead. Everything below is generated from this and Destination City.',
          },
        },
        {
          name: 'destinationCity',
          type: 'text',
          required: true,
          label: 'Destination City',
          admin: {
            width: '50%',
            description: 'Used in H1 and subhead.',
          },
        },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'rate',
          type: 'number',
          required: true,
          label: 'Starting Price (₹)',
          min: 0,
          admin: { width: '40%', description: 'Used in trust checklist item 1 (e.g. "Rates from ₹45 / 500g").' },
        },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'minDeliveryDays',
          type: 'number',
          required: true,
          defaultValue: 1,
          min: 0,
          label: 'Min Delivery Days',
          admin: { width: '50%', description: 'Used in trust checklist item 2.' },
        },
        {
          name: 'maxDeliveryDays',
          type: 'number',
          required: true,
          defaultValue: 2,
          min: 0,
          label: 'Max Delivery Days',
          admin: { width: '50%', description: 'Used in trust checklist item 2.' },
        },
      ],
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      defaultValue: 'active',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
      ],
      admin: { description: 'Whether this route is currently operating.' },
    },
    {
      name: 'published',
      type: 'checkbox',
      label: 'Published',
      defaultValue: true,
      admin: {
        hidden: true,
        description: 'Whether this page is live on the site. Controlled automatically by Status.',
      },
    },
    { name: 'autoInternalTitle', type: 'checkbox', defaultValue: true, admin: { hidden: true } },
    { name: 'autoSlug', type: 'checkbox', defaultValue: true, admin: { hidden: true } },
    { name: 'autoHeroName', type: 'checkbox', defaultValue: true, admin: { hidden: true } },
    { name: 'autoHeroDescription', type: 'checkbox', defaultValue: true, admin: { hidden: true } },
    {
      name: 'internalTitle',
      type: 'text',
      required: true,
      label: 'Title',
      admin: {
        description: 'Auto-generated from origin and destination.',
        components: {
          Field: {
            path: '@/components/admin/AutoGeneratedField#AutoGeneratedField',
            clientProps: { generatorKey: 'internalTitle', autoFieldPath: 'autoInternalTitle' },
          },
        },
      },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: {
        description: 'Auto-generated from origin and destination (e.g. shipping-rates-from-delhi-to-mumbai).',
        components: {
          Field: {
            path: '@/components/admin/AutoGeneratedField#AutoGeneratedField',
            clientProps: { generatorKey: 'slug', autoFieldPath: 'autoSlug' },
          },
        },
      },
    },
    {
      name: 'heroName',
      type: 'text',
      required: true,
      label: 'Hero H1',
      admin: {
        description: 'Standard format: "Shipping Rates from {Origin} to {Destination}".',
        components: {
          Field: {
            path: '@/components/admin/AutoGeneratedField#AutoGeneratedField',
            clientProps: { generatorKey: 'heroName', autoFieldPath: 'autoHeroName' },
          },
        },
      },
    },
    {
      name: 'heroDescription',
      type: 'textarea',
      required: true,
      label: 'Hero Subhead',
      admin: {
        components: {
          Field: {
            path: '@/components/admin/AutoGeneratedField#AutoGeneratedField',
            clientProps: { generatorKey: 'heroDescription', autoFieldPath: 'autoHeroDescription', multiline: true },
          },
        },
      },
    },
    {
      name: 'routeActions',
      type: 'ui',
      label: 'Actions',
      admin: {
        disableListColumn: false,
        components: { Cell: '@/components/admin/RouteActionsCell#RouteActionsCell' },
      },
    },
  ],
}