import { AutoGeneratedField } from '@/components/admin/AutoGeneratedField'
import { RouteActionsCell } from '@/components/admin/RouteActionsCell'

export const importMap = {
  "@/components/admin/AutoGeneratedField#AutoGeneratedField": AutoGeneratedField,
  "@/components/admin/RouteActionsCell#RouteActionsCell": RouteActionsCell,
}
